"use client";

import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "@/styles/dashboard.css";
import { useEffect } from "react";

import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import Theme from "@/components/Theme";

export const metadata = {
  title: "Real State App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    require("bootstrap");
  });

  return (
    <html lang="es">
      <body>
        <Theme />
        <Navbar />
        <div className="container-fluid">
          <div className="row">
            <Sidebar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
